parameters:
#    e_sport_base.example.class: ESport\BaseBundle\Example

services:
#    e_sport_base.example:
#        class: %e_sport_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
